### ISSUE TITLE
I think the code has errors

### ISSUE THREAD

**Issue by jindongwang** [samotiian/CCSA#1]
Hi there, very excellent work!
I reproduce the experiment this afternoon. However, when I run `main.py`, the code doesn't work at all.
It says there is no such file named `./row_data/MNIST_to_USPS_X_train_target_repetition_0_sample_per_class_1.npy`
I checked the disk, there is no such file.
Plus, there is also no 'y_' file. Could you please check the repo?

**Comment by samotiian** [comment]
Thanks for your interest. I think you did not completely download the files in row_data directory. The file ./row_data/MNIST_to_USPS_X_train_target_repetition_0_sample_per_class_1.npy is there. 

You cab double check here:
https://github.com/samotiian/CCSA/tree/master/row_data

**Comment by jindongwang** [comment]
@samotiian You are right! There is something wrong with my downloading (only downloaded 102 out of 840 files, impressive!). Now  I can run the code. Thank you!
