### ISSUE TITLE
Question about the experimental detail

### ISSUE THREAD

**Issue by yusuke0519** [samotiian/CCSA#6]
Hi, thank you for sharing the code! It is beneficial for me to understand the detail of the method. 

I have two questions:
(1) I think your implementation uses Convolutio2D(32, 3, 3). However, the paper says that uses Convolution2D(6, 5, 5), which is inconsistent. Which is correct for reproducing the results? 

Quick Ref: Section 5.1.2 in ICCV paper (https://arxiv.org/pdf/1709.10190.pdf)
> Similar to [37], we used 2 convolutional layers with 6 and 16 filters of 5 × 5 kernels followed by max-pooling layers and 2 fully connected layers with size 120 and 84 ...

(2) Your implementation also uses Dropout in some parts. Is this also used for the reported values?

Thanks.

**Comment by samotiian** [comment]
Unfortunately, I dont recall what structures I used to produce results in the paper. You may rely on the current codes.
