### ISSUE TITLE
Question about results of different repetitions?

### ISSUE THREAD

**Issue by LlywelynapGruffudd** [samotiian/CCSA#7]
Hello! Thank you for sharing the code of CCSA in Github. I'm new to Domain Adaptation and I want to reproduce the result of CCSA. But I have a question.

In MNIST-USPS experiment, the paper says that

> We evaluated our approach for n ranging from 1 to 8 and repeated each experiment 10 times(we only show the mean of the accuracies because the standard deviation is very small). 

Ref: Section 5.1.2 in ICCV paper (https://arxiv.org/pdf/1709.10190.pdf)

But the results between different repetitions in my reproduced is not very small?(acc between 86 and 94)?Is that normal?

Please forgive me if I ask a silly question.

**Comment by samotiian** [comment]
It depends on a lot of factors including the initialization and learning rate. I dont recall how I got those results as the paper is more than two years old.

**Comment by LlywelynapGruffudd** [comment]
Thank you all the same
